export const Users = [
  {
    id: "1",
    name: "John Doe",
    img: "/person/2.jpeg",
    email: "john@example.com",
    slug: "john-doe",
    role: "admin",
    status: true,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "2",
    name: "Jane Smith",
    img: "/person/1.jpeg",
    email: "jane@example.com",
    slug: "jane-smith",
    role: "client",
    status: false,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "3",
    name: "Alice Johnson",
    img: "/person/3.jpeg",
    email: "alice@example.com",
    slug: "alice-johnson",
    role: "client",
    status: true,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "4",
    name: "Bob Brown",
    img: "/person/4.jpeg",
    email: "bob@example.com",
    slug: "bob-brown",
    role: "client",
    status: false,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "5",
    name: "Charlie Davis",
    img: "/person/5.jpeg",
    email: "charlie@example.com",
    slug: "charlie-davis",
    role: "client",
    status: true,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "6",
    name: "David Green",
    img: "/person/6.jpeg",
    email: "david@example.com",
    slug: "david-green",
    role: "client",
    status: false,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "7",
    name: "Eva White",
    img: "/person/7.jpeg",
    email: "eva@example.com",
    slug: "eva-white",
    role: "client",
    status: true,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
  {
    id: "8",
    name: "Frank Black",
    img: "/person/8.jpeg",
    email: "frank@example.com",
    slug: "frank-black",
    role: "admin",
    status: false,
    createdAt: "2019-08-30T13:46:57.783Z",
  },
];

export const Products = [
  {
    id: 1,
    title: "Pantalon en denim wide leg - Bleu",
    description: "Ce pantalon donne un style décontracté à toutes vos tenues !",
    price: "15.00",
    image: [
      "/products/jeans/pantalon-en-denim.webp",
      "/products/jeans/pantalon-en-denim2.webp",
      "/products/jeans/pantalon-en-denim3.webp",
    ],
    slug: "pantalon-en-denim-wide-leg-Bleu",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 10,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 2,
    title: "T-shirt droit en jersey uni - blanc",
    description:
      "Celui qui s'associe aussi bien avec un jean qu’un pantalon plus habillé.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-droit-en-jersey.webp",
      "/products/t-shirts/t-shirt-droit-en-jersey2.webp",
      "/products/t-shirts/t-shirt-droit-en-jersey3.webp",
    ],
    slug: "t-shirt-droit-en-jersey-uni-blanc",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    stock: 5,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 3,
    title: "Veste esprit campus - Noir",
    description:
      "La veste esprit campus, un indispensable de votre dressing, en molleton gratté (doux et chaud) !",
    price: "25.00",
    image: [
      "/products/vestes/veste-esprit-campus.webp",
      "/products/vestes/veste-esprit-campus2.webp",
      "/products/vestes/veste-esprit-campus3.webp",
    ],
    slug: "veste-esprit-campus-Noir",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 0,
    inStock: false,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 4,
    title: "Chaussures de ville - Noir",
    description:
      "Chaussures de ville en cuir, à lacets, avec semelle en caoutchouc.",
    price: "35.00",
    image: [
      "/products/chaussures/chaussures-de-ville-noir.webp",
      "/products/chaussures/chaussures-de-ville-noir2.webp",
      "/products/chaussures/chaussures-de-ville-noir3.webp",
    ],
    slug: "chaussures-de-ville-Noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 10,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 5,
    title: "Jean slim - L32 - stone used",
    description:
      "Le basique qu'il faut avoir absolument dans son dressing, couleur beige !",
    price: "17",
    image: [
      "/products/jeans/jean-slim.webp",
      "/products/jeans/jean-slim2.webp",
      "/products/jeans/jean-slim3.webp",
    ],
    slug: "jean-slim-L32-stone-used",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["red", "black", "blue"],
    stock: 8,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 6,
    title: "Jean skinny fit / coupe très ajustée - Rince",
    description: "Un jean skinny comme une seconde peau !",
    price: "19.99",
    image: [
      "/products/jeans/jean-skinny-fit.webp",
      "/products/jeans/jean-skinny-fit2.webp",
      "/products/jeans/jean-skinny-fit3.webp",
    ],
    slug: "jean-skinny-fit-coupe-tres-ajustee-Rince",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 6,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 7,
    title: "Jean slim à 5 poches - bleu marine",
    description: "Un jean slim, parfait pour lui et ses mouvements !",
    price: "12.99",
    image: [
      "/products/jeans/jean-slim-a-5-poches.webp",
      "/products/jeans/jean-slim-a-5-poches2.webp",
      "/products/jeans/jean-slim-a-5-poches3.webp",
    ],
    slug: "jean-slim-a-5-poches-bleu-marine",
    catSlug: "jeans",
    cat: "jeans",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 3,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 8,
    title: "T-shirt droit en jersey uni - blanc",
    description: "Best sellers* : L'incontournable T-shirt basique.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-droit.webp",
      "/products/t-shirts/t-shirt-droit2.webp",
      "/products/t-shirts/t-shirt-droit3.webp",
    ],

    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    stock: 0,
    inStock: false,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 9,
    title: "T-shirt droit en jersey uni - Noir",
    description:
      "Les meilleures ventes : L'incontournable pour un bon basique.",
    price: "4.00",
    image: [
      "/products/t-shirts/t-shirt-uni-en-jersey.webp",
      "/products/t-shirts/t-shirt-uni-en-jersey2.webp",
      "/products/t-shirts/t-shirt-uni-en-jersey3.webp",
    ],
    slug: "t-shirt-droit-en-jersey-uni-Noir",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    stock: 10,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 10,
    title: "T-shirt col V - noir",
    description: "Un basique très confortable !",
    price: "6.00",
    image: [
      "/products/t-shirts/t-shirt-col-v.webp",
      "/products/t-shirts/t-shirt-col-v2.webp",
      "/products/t-shirts/t-shirt-col-v3.webp",
    ],
    slug: "t-shirt-col-v-noir",
    catSlug: "t-shirts",
    cat: "t-shirts",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    stock: 5,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 11,
    title: "Gilet sans manches en sherpa - Marron",
    description: "Le gilet de base pour les plus petits et les plus grands.",
    price: "12.00",
    image: [
      "/products/vestes/gilet-sans-manches.webp",
      "/products/vestes/gilet-sans-manches2.webp",
      "/products/vestes/gilet-sans-manches3.webp",
    ],
    slug: "gilet-sans-manches-en-sherpa-marron",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "yellow"],
    stock: 6,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 12,
    title: "Veste en jean avec manches en molleton - Bleu",
    description: "Veste en jean avec manches en molleton - Bleu",
    price: "25.00",
    image: [
      "/products/vestes/veste-en-jean.webp",
      "/products/vestes/veste-en-jean2.webp",
      "/products/vestes/veste-en-jean3.webp",
    ],
    slug: "veste-en-jean-avec-manches-en-molleton-bleu",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 2,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 13,
    title: "Veste bi matière - Kaki",
    description: "Veste bi matière - Kaki",
    price: "25.00",
    image: [
      "/products/vestes/veste-bi-matiere.webp",
      "/products/vestes/veste-bi-matiere2.webp",
      "/products/vestes/veste-bi-matiere3.webp",
    ],
    slug: "veste-bi-matiere-kaki",
    catSlug: "vestes",
    cat: "vestes",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 3,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 14,
    title: "Bottines type chelsea - Noir",
    description: "Bottines type chelsea - Noir",
    price: "25.00",
    image: [
      "/products/chaussures/bottines-type-chelsea-noir.webp",
      "/products/chaussures/bottines-type-chelsea-noir2.webp",
      "/products/chaussures/bottines-type-chelsea-noir3.webp",
    ],
    slug: "bottines-type-chelsea-noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 4,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 15,
    title: "Escarpins babies vernis - Noir",
    description: "Escarpins babies vernis - Noir",
    price: "25.00",
    image: [
      "/products/chaussures/escarpins-babies-vernis-noir.webp",
      "/products/chaussures/escarpins-babies-vernis-noir2.webp",
      "/products/chaussures/escarpins-babies-vernis-noir3.webp",
    ],
    slug: "escarpins-babies-vernis-noir",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 5,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
  {
    id: 16,
    title: "Chaussures de randonnée - kaki",
    description: "Chaussures de randonnée - kaki",
    price: "25.00",
    image: [
      "/products/chaussures/chaussures-de-randonnee.webp",
      "/products/chaussures/chaussures-de-randonnee2.webp",
      "/products/chaussures/chaussures-de-randonnee3.webp",
    ],
    slug: "chaussures-de-randonnee-kaki",
    catSlug: "chaussures",
    cat: "chaussures",
    size: ["S", "M", "L"],
    color: ["white", "black", "blue"],
    stock: 6,
    inStock: true,
    active: true,
    createdAt: "2021-05-01T00:00:00.000Z",
  },
];

export const Orders = [
  {
    id: "1",
    amount: 100.0,
    createdAt: "2019-08-30T13:46:57.783Z",
    status: "terminé",
  },
  {
    id: "2",
    amount: 200.0,
    createdAt: "2019-08-30T13:46:57.783Z",
    status: "en cours",
  },
  {
    id: "3",
    amount: 300.0,
    createdAt: "2019-08-30T13:46:57.783Z",
    status: "terminé",
  },
  {
    id: "4",
    amount: 400.0,
    createdAt: "2019-08-30T13:46:57.783Z",
    status: "en cours",
  },
];

export const fetchUsers = (q, page) => {
  const regex = new RegExp(q, "i");

  const ITEM_PER_PAGE = 2;

  try {
    const count = Users.find({ username: { $regex: regex } }).count();
    const users = Users.find({ username: { $regex: regex } })
      .limit(ITEM_PER_PAGE)
      .skip(ITEM_PER_PAGE * (page - 1));
    return { count, users };
  } catch (err) {
    console.log(err);
    throw new Error("Failed to fetch users!");
  }
};
